# requires read.meta.yml to be processed earlier
pipeline:
  find:
    include:
      <$ for(const name of Object.keys(ctx.meta.projects)) { $>
      - ../../<$- name $>/package.json
      <$ } $>
    result:
      assignTo: '$.ctx.packageJsonFiles'