
description: |
  FBL script that allows to run git command over every selected repository.

requires:
  applications:
    - git

pipeline:
  '--':
    - '@': 'utilities/read.meta.yml'
    - '@': 'utilities/select.repos.yml'
    - each:
        of: $ref:ctx.selected
        action:
          $parameters:
            path: ../<%- iteration.value %>            
          '--':
            - echo: 'Running "git <$- parameters.args.join(' ') $>" over <%- parameters.path %>'            
            - exec:
                command: git
                args: $ref:parameters.args                  
                wd: $ref:parameters.path
                options:
                  verbose: true