# VSCode in unable to highlight VCS changes in meta repository
# To bypass that limitation this simple script generated .gitmodules file based on .meta content
# Note: make sure .gitmodules file is git ignored.
pipeline:
  '--':
    - '@': 'utilities/read.meta.yml'
    - '->':
        path: ../.gitmodules
        content: |
          <% for(const name of Object.keys(ctx.meta.projects)) { %>[submodule "<%- name %>"]
          	path = <%- name %>
            url = <%- ctx.meta.projects[name] %>
            
          <% } %>